import { Eye, EyeOff, Lock, Mail, ShieldAlert, X } from 'lucide-react'
import { useMemo, useState } from 'react'
import ToggleSwitch from './ToggleSwitch'
import { useConfirmDialog } from './ConfirmModal'
import { useToast } from './Toast'
import { studentManager } from '../lib/manageStudent'
import { supabase } from '../lib/supabase'
import { initials } from '../lib/utils'

const tabs = ['Profile', 'Security', 'Danger Zone']

export default function EditStudentPanel({ student, onClose, onSaved }) {
  const [activeTab, setActiveTab] = useState('Profile')
  const [form, setForm] = useState(() => ({ ...student }))
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [busy, setBusy] = useState(false)
  const { confirm, ConfirmDialog } = useConfirmDialog()
  const { showToast } = useToast()
  const strength = useMemo(() => passwordStrength(password), [password])

  async function saveProfile() {
    setBusy(true)
    try {
      const emailChanged = form.email && form.email !== student.email
      if (emailChanged) await studentManager.changeEmail(student.id, form.email)
      const { error } = await supabase.from('profiles').update({
        full_name: form.full_name,
        email: form.email,
        university: form.university,
        course: form.course,
        student_id: form.student_id
      }).eq('id', student.id)
      if (error) throw error
      showToast('Student profile saved.', 'success')
      onSaved?.()
    } catch (err) {
      showToast(err.message || 'Profile could not be saved.', 'error')
    } finally {
      setBusy(false)
    }
  }

  async function changePassword() {
    if (password.length < 8) return showToast('Password must be at least 8 characters.', 'error')
    setBusy(true)
    try {
      await studentManager.changePassword(student.id, password)
      setPassword('')
      showToast('Password changed.', 'success')
    } catch (err) {
      showToast(err.message || 'Password could not be changed.', 'error')
    } finally {
      setBusy(false)
    }
  }

  async function sendResetEmail() {
    setBusy(true)
    try {
      await studentManager.sendResetEmail(student.id)
      showToast('Reset email generated by Supabase.', 'success')
    } catch (err) {
      showToast(err.message || 'Reset email could not be sent.', 'error')
    } finally {
      setBusy(false)
    }
  }

  async function setActive(nextActive) {
    const message = nextActive
      ? 'This student will be able to log in again.'
      : 'This student will be blocked from logging in, but their data is preserved.'
    if (!await confirm({ title: nextActive ? 'Reactivate account?' : 'Deactivate account?', message, confirmText: nextActive ? 'Reactivate' : 'Deactivate' })) return
    setBusy(true)
    try {
      if (nextActive) await studentManager.reactivate(student.id)
      else await studentManager.deactivate(student.id)
      setForm(prev => ({ ...prev, is_active: nextActive }))
      showToast(nextActive ? 'Account reactivated.' : 'Account deactivated.', 'success')
      onSaved?.()
    } catch (err) {
      showToast(err.message || 'Account access could not be updated.', 'error')
    } finally {
      setBusy(false)
    }
  }

  async function deleteAccount() {
    if (!await confirm({ title: 'Delete account permanently?', message: 'This deletes the student account and all linked academic data. This cannot be undone.', confirmText: 'Delete account' })) return
    if (!await confirm({ title: 'Final confirmation', message: `Delete ${student.full_name || student.email} forever?`, confirmText: 'Yes, delete' })) return
    setBusy(true)
    try {
      await studentManager.deleteAccount(student.id)
      showToast('Student account deleted.', 'success')
      onSaved?.()
      onClose()
    } catch (err) {
      showToast(err.message || 'Account could not be deleted.', 'error')
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm" onClick={onClose}>
      <aside className="animate-slideInRight absolute bottom-0 right-0 top-0 flex w-full max-w-xl flex-col border-l border-white/10 bg-navy-900 shadow-2xl" onClick={e => e.stopPropagation()}>
        <header className="border-b border-white/10 p-5">
          <div className="flex items-start justify-between gap-4">
            <div className="flex min-w-0 items-center gap-3">
              <Avatar student={form} size="h-14 w-14 text-lg" />
              <div className="min-w-0">
                <h2 className="truncate text-lg font-bold">{form.full_name || 'Unnamed student'}</h2>
                <p className="truncate text-sm text-slate-400">{form.email}</p>
              </div>
            </div>
            <button className="rounded-lg p-2 text-slate-400 hover:bg-white/5" onClick={onClose}><X className="h-5 w-5" /></button>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            <span className={`rounded-full px-3 py-1 text-xs font-medium ${form.is_active === false ? 'bg-red-500/15 text-red-300' : 'bg-emerald-500/15 text-emerald-300'}`}>
              {form.is_active === false ? 'Deactivated' : 'Active'}
            </span>
            {form.course && <span className="rounded-full bg-amber-500/15 px-3 py-1 text-xs font-medium text-amber-300">{form.course}</span>}
          </div>
        </header>
        <nav className="grid grid-cols-3 gap-2 border-b border-white/10 p-3">
          {tabs.map(tab => (
            <button key={tab} onClick={() => setActiveTab(tab)} className={`min-h-[44px] rounded-xl text-sm font-medium ${activeTab === tab ? 'bg-amber-500 text-white' : 'text-slate-400 hover:bg-white/5'}`}>
              {tab}
            </button>
          ))}
        </nav>
        <div className="scrollbar-hide flex-1 overflow-y-auto p-5">
          {activeTab === 'Profile' && (
            <div className="space-y-4">
              <Field label="Full Name"><input className="input" value={form.full_name || ''} onChange={e => setForm({ ...form, full_name: e.target.value })} /></Field>
              <Field label="Email"><input className="input" type="email" value={form.email || ''} onChange={e => setForm({ ...form, email: e.target.value })} /></Field>
              <p className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-200">Changing email updates the student's login credentials through the secure Edge Function.</p>
              <Field label="University"><input className="input" value={form.university || ''} onChange={e => setForm({ ...form, university: e.target.value })} /></Field>
              <Field label="Course / Programme"><input className="input" value={form.course || ''} onChange={e => setForm({ ...form, course: e.target.value })} /></Field>
              <Field label="Student ID"><input className="input" value={form.student_id || ''} onChange={e => setForm({ ...form, student_id: e.target.value })} /></Field>
              <button className="manager-primary-btn w-full" disabled={busy} onClick={saveProfile}>Save Profile Changes</button>
            </div>
          )}
          {activeTab === 'Security' && (
            <div className="space-y-5">
              <section className="rounded-xl border border-white/10 p-4">
                <h3 className="mb-3 flex items-center gap-2 font-semibold"><Lock className="h-4 w-4 text-amber-400" /> Set New Password</h3>
                <div className="relative">
                  <input className="input pr-12" type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} />
                  <button className="absolute right-1 top-0 rounded-lg text-slate-400" onClick={() => setShowPassword(v => !v)}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button>
                </div>
                <div className="mt-3 grid grid-cols-5 gap-1">
                  {[0, 1, 2, 3, 4].map(i => <span key={i} className={`h-2 rounded-full ${i < strength.score ? strength.color : 'bg-white/10'}`} />)}
                </div>
                <p className="mt-2 text-xs text-slate-400">{strength.label}</p>
                <button className="manager-primary-btn mt-4 w-full" disabled={busy} onClick={changePassword}>Change Password</button>
              </section>
              <section className="rounded-xl border border-white/10 p-4">
                <h3 className="mb-2 flex items-center gap-2 font-semibold"><Mail className="h-4 w-4 text-amber-400" /> Send Reset Email</h3>
                <p className="muted mb-3">Send a password reset link to {form.email}. The student resets it themselves.</p>
                <button className="btn-ghost w-full" disabled={busy} onClick={sendResetEmail}>Send Reset Email to Student</button>
              </section>
              <section className="rounded-xl border border-white/10 p-4">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <h3 className="font-semibold">Allow student to log in</h3>
                    <p className="muted">Turn access on or off without deleting records.</p>
                  </div>
                  <ToggleSwitch isOn={form.is_active !== false} onToggle={() => setActive(form.is_active === false)} />
                </div>
                {form.is_active === false && <p className="mt-3 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-300">This student cannot log in.</p>}
              </section>
            </div>
          )}
          {activeTab === 'Danger Zone' && (
            <div className="space-y-4">
              <div className="rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">
                <ShieldAlert className="mb-2 h-5 w-5" />
                Destructive actions affect account access and student data. Confirm carefully before continuing.
              </div>
              <section className="rounded-xl border border-white/10 p-4">
                <h3 className="font-semibold">{form.is_active === false ? 'Reactivate Account' : 'Deactivate Account'}</h3>
                <p className="muted mt-1">Deactivation blocks login while preserving records.</p>
                <button className="btn-ghost mt-4 w-full border-amber-500/40 text-amber-300" disabled={busy} onClick={() => setActive(form.is_active === false)}>
                  {form.is_active === false ? 'Reactivate Account' : 'Deactivate Account'}
                </button>
              </section>
              <section className="rounded-xl border border-red-500/30 bg-red-500/10 p-4">
                <h3 className="font-semibold text-red-200">Permanently Delete Account</h3>
                <p className="mt-1 text-sm text-red-200/80">Deletes account and linked academic data. This cannot be undone.</p>
                <button className="mt-4 min-h-[48px] w-full rounded-xl bg-red-600 px-4 py-3 font-semibold text-white hover:bg-red-500" disabled={busy} onClick={deleteAccount}>Delete Account Permanently</button>
              </section>
            </div>
          )}
        </div>
      </aside>
      {ConfirmDialog}
    </div>
  )
}

function Field({ label, children }) {
  return <label className="block"><span className="label">{label}</span>{children}</label>
}

function Avatar({ student, size = 'h-10 w-10' }) {
  return <div className={`grid shrink-0 place-items-center rounded-full font-semibold text-white ${size}`} style={{ background: student.avatar_color || '#F59E0B' }}>{initials(student.full_name || student.email)}</div>
}

function passwordStrength(value) {
  let score = 0
  if (value.length >= 8) score += 1
  if (/[A-Z]/.test(value)) score += 1
  if (/[0-9]/.test(value)) score += 1
  if (/[^A-Za-z0-9]/.test(value)) score += 1
  if (value.length >= 12) score += 1
  const labels = ['Weak', 'Weak', 'Fair', 'Good', 'Strong', 'Very Strong']
  const colors = ['bg-red-500', 'bg-red-500', 'bg-orange-500', 'bg-yellow-500', 'bg-green-500', 'bg-emerald-500']
  return { score: Math.max(1, score), label: labels[score], color: colors[score] }
}
